services:
  rails-app:
    build:
      context: .
      args:
        RUBY_VERSION: 3.2.2
    container_name: rails-app
    ports:
      - "3000:3000"
    volumes:
      - rails-data:/rails/db
      - .:/rails
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: "benoitswag"

volumes:
  rails-data:
